# Generated by Django 5.0.2 on 2024-03-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='tagged_pets',
            new_name='pets',
        ),
    ]
