# Generated by Django 5.0.2 on 2024-03-11 12:02

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_tagged_pets_photo_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
