# Generated by Django 5.0.2 on 2024-03-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0002_rename_tagged_pets_photo_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_time_of_publication',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.photo'),
        ),
    ]
