# Generated by Django 5.0.2 on 2024-03-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_date_time_of_publication_comment_created_at_and_more'),
        ('photos', '0002_rename_tagged_pets_photo_pets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='PhotoLike',
        ),
    ]
