# Generated by Django 5.0.2 on 2024-03-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_like_photolike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='to_photo',
            new_name='pet_photo',
        ),
    ]
