# Generated by Django 5.0.2 on 2024-03-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_to_photo_comment_pet_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photolike',
            old_name='to_photo',
            new_name='pet_photo',
        ),
    ]
