# Generated by Django 5.0.2 on 2024-03-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='personal_photo',
            new_name='pet_photo',
        ),
    ]
